import { Dimensions, Platform } from "react-native";
import { Colors } from "./CustomColor";

export const CustomStyles = {
  customButtonContainer: {
    top: -30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: Colors.black,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  customButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primaryblue,
    elevation: 5,
    shadowColor: Colors.black,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  logoContainerUpper: {
    flex: 0.35,
    alignItems: "center",
  },
  forgotHeaderContainer: {
    paddingTop: 30,
    alignItems: "center",
  },
  headerTitleWhite: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.white,
  },
  profileImageContainer: {
    alignItems: "center",
    position: "absolute",
    left: 0,
    right: 0,
    top: "65%",
  },
  profileImage: {
    width: 200,
    height: 200,
    backgroundColor: Colors.gray1,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  camera: {
    position: "absolute",
    top: 50,
    bottom: 0,
    left: "68%",
    right: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Colors.primaryblue,
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
  },
  generalContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  profileContainer: {
    flex: 0.65,
    paddingHorizontal: 24,
    justifyContent: "space-between",
  },
  profileBottomContainer: {
    paddingTop: 224,
  },
  divider: {
    height: 1.5,
    marginVertical: 12,
  },
  dividerNoUpperMargin: {
    height: 1.5,
    marginBottom: 12,
  },
  descriptionTextMedium: {
    color: Colors.gray4,
    fontSize: 12,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  descriptionTextMediumLight: {
    color: Colors.gray2,
    fontSize: 13,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  priceTextLarge: {
    color: Colors.lightBlack,
    fontSize: 15,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  infoContainer: {
    flexDirection: "row",
    //alignItems: "center",
  },
  profileIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  titleouter: {},
  titleinner: {
    fontSize: 20,
    color: Colors.black,
    fontFamily: "poppins-medium",
  },
  generalContainerPadding: {
    flex: 1,
    paddingTop: 32,
    paddingHorizontal: 24,
    backgroundColor: Colors.white,
  },
  generalContainerMargin: {
    flex: 1,
    //marginTop: 32,
    paddingHorizontal: 24,
    backgroundColor: Colors.white,
  },
  infoOuterContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoOuterContainerMargin: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 32,
  },
  bottomZoloContainer: {
    paddingTop: 32,
  },
  logoContainer: {
    width: "100%",
    height: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  zoloImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  searchContainer: {
    marginTop: 8,

    borderColor: Colors.gray2,
    borderWidth: 2,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  locationButtonContainer: {
    flexDirection: "row",
    marginVertical: 4,
    alignItems: "center",
  },
  cityText: {
    color: Colors.lightblue,
    marginRight: 6,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  headerIcons: {
    marginLeft: 24,
    marginTop: 2,
  },
  listTitle: {
    fontSize: 17,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  listDescription: {
    fontSize: 12,
    color: Colors.gray4,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  viewall: {
    fontSize: 13,
    color: Colors.primaryblue,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  pressed: {
    opacity: 0.7,
  },
  listContainer: {
    flex: 1,
    backgroundColor: Colors.gray1,
    borderRadius: 12,
  },
  cardImageContainer: {
    width: 180,
    height: 120,
    borderRadius: 12,
    borderTopRightRadius: 12, //marginVertical: 6,
  },
  cardImageContainerVertical: {
    width: "100%",
    height: 220,
    borderRadius: 12,
    borderTopRightRadius: 12, //marginVertical: 6,
  },
  cardImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    overflow: "hidden",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  dealsContainer: {
    // backgroundColor: Colors.appBackground,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  carousel: {
    marginTop: 24,
    width: "100%",
  },
  cardContainer: {
    flex: 1,
    marginHorizontal: 6,
    borderRadius: 12,
    backgroundColor: Colors.appBackground,
  },
  cardContainerVertical: {
    flex: 1,
    marginVertical: 16,
    borderRadius: 12,
    backgroundColor: Colors.appBackground,
  },
  cardTitleText: {
    fontSize: 15,
    //fontWeight: "500",
    color: Colors.black,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  cardDescriptionText: {
    fontSize: 12,
    // fontWeight: "500",
    color: Colors.gray4,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  priceText: {
    fontSize: 18,
    //fontWeight: "500",
    color: Colors.black,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    marginRight: 4,
  },
  customButtonContainer: {
    position: "absolute",
    bottom: 80,
    right: 50,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.primaryblue,
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 30,
    borderRadius: 30,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  imageContainerLarge: {
    width: Dimensions.get("window").width,
    height: 300,
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "stretch",
  },
  iconContainers: {
    position: "absolute",
    top: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    width: "100%",
  },
  mainContainer: {
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  titleTextLarge: {
    fontSize: 18,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.black,
  },
  priceTextLarge: {
    color: Colors.gray3,
    fontSize: 13,
    fontFamily: "poppins-medium",
  },
  descriptionTextMedium: {
    color: Colors.gray3,
    fontSize: 14,
    fontFamily: "poppins-regular",
  },
  dividerShort: {
    height: 4,
    marginTop: 32,
    width: 150,
    alignSelf: "center",
    backgroundColor: Colors.gray2,
  },
  buildingImage: {
    width: 70,
    height: 70,
    resizeMode: "cover",
    marginRight: 12,
  },
  signatureDescription: {
    fontSize: 12,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.gray3,
    maxWidth: "95%",
    marginTop: 8,
  },
  propertyContainer: {
    marginTop: 12,
    flexWrap: "wrap",
    flexDirection: "row",
  },
  propertyImageContainer: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  propertyItem: {
    marginHorizontal: 6,

    alignItems: "center",
  },
  propertyImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  propertyText: {
    fontSize: 12,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.gray4,
    maxWidth: "100%",
    textAlign: "center",
  },
  propertyTextLeft: {
    fontSize: 12,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.gray4,
    maxWidth: "100%",
  },
  propertyTextContainer: {
    width: 60,
    marginBottom: 16,
  },
  propertiesButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.gray1,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
    marginBottom: 12,
  },
  rowWithMargin: {
    flexDirection: "row",
    marginVertical: 12,
  },
  roomTitle: {
    fontSize: 14,
    fontFamily: "poppins-regular",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.lightBlack,
  },
  priceTextSmall: {
    fontSize: 15,
    //fontWeight: "500",
    color: Colors.black,
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    marginRight: 4,
  },

  descriptionTextMediumSmall: {
    color: Colors.gray3,
    fontSize: 12,
    fontFamily: "poppins-regular",
    textAlignVertical: "bottom",
  },
  marginTop6: {
    marginTop: 6,
  },
  bottomDescriptionBar: {
    alignItems: "center",
    justifyContent: "space-between",
    height: "8%",
    position: "absolute",
    bottom: 0,
    backgroundColor: "white",
    width: "100%",
    borderTopColor: "#e6e5e3",
    borderTopWidth: 2,
    paddingHorizontal: 24,
    flexDirection: "row",
  },
  selectRoomButton: {
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.primaryblue,
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 30,
    borderRadius: 30,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },

  centered: {
    justifyContent: "center",
  },
  labelcontainer: {
    marginVertical: 10,
  },
  labeltext: {
    color: Colors.lightBlack,
    fontSize: 14,
    fontFamily: "poppins-regular",
    // marginBottom: 4,
  },
  textInput: {
    width: "100%",
    height: 50,
    borderRadius: 12,
    borderTopColor: Colors.white,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderBottomColor: Colors.gray1,
    borderLeftWidth: 2,
    borderLeftColor: Colors.gray1,
    borderRightWidth: 2,
    borderRightColor: Colors.gray1,
    paddingHorizontal: 18,
    fontSize: 16,
    color: Colors.gray5,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    flexDirection: "row",
    backgroundColor: Colors.lightblue,
  },
  whiteTitle: {
    color: Colors.white,
    textAlign: "center",
  },
  marginRight6: {
    marginRight: 6,
  },
  submitButtonOuter: {
    marginVertical: 120,
  },
  submitButton: {
    paddingHorizontal: 24,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: Colors.primaryblue,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButtonText: {
    fontSize: 16,
    fontFamily: "poppins-medium",
    color: Colors.white,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  error: {
    paddingVertical: 4,
    fontSize: 12,
    fontFamily: "poppins-regular",
    color: "red",
  },
  uploadImageContainer: {
    height: 200,
    borderRadius: 12,
    backgroundColor: Colors.gray1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  uploadImageText: {
    fontFamily: "poppins-medium",
    color: Colors.gray4,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  uploadedImageContainer: {
    width: Dimensions.get("window").width - 48,
    height: 200,
    borderRadius: 12,
    backgroundColor: "transparent",
    marginBottom: 12,
  },
  uploadedImage: {
    width: "100%",
    height: "100%",
    resizeMode: "stretch",
  },
  marginBottom: {
    paddingBottom: "20%",
  },
  searchTextInputContainer: {
    marginTop: 32,
    borderColor: Colors.gray2,
    borderWidth: 2,
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  searchTextInput: {
    flex: 10,
    fontSize: 15,
    fontFamily: "poppins-medium",
    color: Colors.gray4,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  ListContainer: {
    paddingVertical: 8,
    flexDirection: "row",
  },
};
