export const CustomStrings = {
  str01: "Search a location, name or gender",
  str02: "Featured Properties",
  str03: "Explore Top Properties",
  str04: "Select Properties",
  str05:
    "Zolo Properties are premium offerings comparable to luxurious apartments",
  str06: "This is a signature property",
  str07:
    "Premium properties, amenities and neighbourhood. No more hefty deposits, exorbitant rents and miserly landlords.",
  str08: "10+",
  str09: "17500",
  str10: "10500",
  str11: "Private Room",
  str12: "Two Sharing",
  str13: "Breakfast",
  str14: "Dinner",
  str15: "Daily",
  str16: "Weekends",
  str17: "Note: Food is served in the common dinning area.",
  str18: "Monthly Rent Breakup",
  str19: "About the Property",
  str20:
    "A quick 5 minutes walk away from Christ College\non Hosur road, Zolo Knight has all one needs. Fully\nfurnished flats, lightning fast wifi, housekeeping",
  str21: "Token Amount",
  str22: "1000",
  str23: "Select Room",
  str24: "Add PG",
  str25: "Name",
  str26: "Location",
  str27: "Suitable for",
  str28: "Price",
  str29: "Description",
  str30: "Submit",
  str31: "My Bookings",
};
